# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

/*ä¸»è¦æ›¿æ¢çš„å­—ç¬¦ğŸ‘‡


å°ä¹        //jsåå­—
0 0-15    //å®šæ—¶ï¼Œå¦‚åŒ—äº¬æ—¶é—´8åˆ°23ç‚¹ï¼Œè®¾ç½®0-15
XL_URL    //ç¯å¢ƒå˜é‡ä¹‹ä¸€ï¼Œ26è¡Œå¤„è‡ªè¡Œæ·»åŠ å…¶ä»–
ABC        //è´¦å·å
JavaScript       //ä»“åº“å
Task/xiaole.js    //å­æ–‡ä»¶åœ°å€


*/

name: ç¬‘è°±

on:
  workflow_dispatch:
  schedule:
     - cron: '30 0-15 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN }}
        XP_CASH: ${{ secrets.XP_CASH }}
        XP_live: ${{ secrets.XP_live }}	
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/tommyhe1217/JavaScript.git ~/JavaScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XL_URL
        run: |
          cd ~/JavaScript
          npm install
      - name: 'è¿è¡Œ ã€ç¬‘è°±ã€‘'
        if: env.XL_URL
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
